#!/bin/bash

check=$(pgrep arpwatch|wc -l)


if [ $check -eq 1 ]
then
	echo "Arpwatch is running."
	exit 0
elif [ $check -eq 0 ]
then
	echo "Arpwatch is NOT running!"
	exit 2
else
	echo "Arpwatch is an unknown state."
	exit 1
fi
